name: Update YouTube Videos

on:
 # schedule:
 #   - cron: '0 0 * * *' # This will run the workflow every day at midnight
 workflow_dispatch: # This allows you to manually trigger the workflow from GitHub's UI

jobs:
 update-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch YouTube videos
        run: python .github/scripts/fetch_youtube_videos.py
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }} # Pass the API key as an environment variable
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }} # Pass the channel ID as an environment variable

      - name: Update README.md
        run: python .github/scripts/update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update YouTube videos"
          git push